### ISSUE TITLE
Connect to FaceBook account kit

### ISSUE THREAD

**Issue by MakarkinPRO** [dderevjanik/wordpress-jwt-auth#2]
Any ideas or plans to connect with FaceBook account kit (sms registrer/auth_) ?

**Comment by dderevjanik** [comment]
Hi,
there's no plan for connect with facebook account kit, beause it's out of scope of this project. This project is only wrapper above [wp-api-jwt-auth](https://github.com/Tmeister/wp-api-jwt-auth).
